server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/food}
    hikari:
      validation-timeout: '3000'
      idle-timeout: '60000'
      maximum-pool-size: '500'
      max-lifetime: '1800000'
      connection-timeout: '600000'
      minimum-idle: '20'
    
  application:
    name: Good Food Service
  jpa:
    hibernate:
      ddl-auto: update
  flwyay:
    validateMigrationNaming: false
    locations: classpath:db/migration

food:
  integration:
    product:
      name: goodfood-product 
      url: svc-goodfood-product-postech-loadbalancer:8080
    payment:
      name: goodfood-payment 
      url: svc-goodfood-payment-postech-loadbalancer:8080
